### ISSUE TITLE
how about test speed

### ISSUE THREAD

**Issue by liuheng92** [Siyu-C/ACAR-Net#12]
hi, thanks for your awewsome work. Can you tell me about model test speed? Count on input video resolution, video duration , fps and so on.

**Comment by Siyu-C** [comment]
Hi @liuheng92 , test speed can vary due to many factors. The most important factor would be data loading speed, since the model inference part is generally quite fast, and the data time may dominate. The time spent on data further depends on the number (duration) and resolution of frames extracted from the input video. In terms of fps, we fix it to be 30 when extracting frames.
