### ISSUE TITLE
Question about computing resources

### ISSUE THREAD

**Issue by Jia-Wei-Liu** [Siyu-C/ACAR-Net#27]
Nice work and thank you for sharing your code!
Could you please tell me about your computing resources on this task? E.g., how many and what type of GPU did you use and how long is the training time? Thank you!

**Comment by Siyu-C** [comment]
Hi @Jia-Wei-Liu, as is stated in our paper, our default setting set total mini-batch size to 32, so we train with 32 GPUs per experiment since batch size per GPU is 1. For a model with SlowFast R-50 as backbone, assume data loading does not become the bottleneck, training time per epoch should be less than 1.5h on any common type of GPU devices.

**Comment by JialianW** [comment]
> 

May I know how many epochs you need? And what is the total training time in hours using the 32 GPUs? Thanks!
